try
{
    eval("console.log((()=>'test')())");
    alert("err");
}
catch (err)
{
    alert(err);
}

// alert('1');
// console.log("err");